spring:
  application:
    name: 01-fundamentos-configuracion

dfc:
  app:
    message: "Configuración por defecto (sin perfil específico)"
  features:
    extra-endpoint: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
